name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14.x'
      - run: npm install 
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test



  move_files:
    runs-on: ubuntu-latest
    steps:
      - name: work on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{secrets.SERVER_USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}

          script: |
            ls 
            whoami 
